SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IN (
	SELECT ANIMAL_ID
	FROM ANIMAL_INS
	WHERE SEX_UPON_INTAKE LIKE 'Intact%'
)
AND B.ANIMAL_ID NOT IN (
	SELECT ANIMAL_ID
	FROM ANIMAL_OUTS
	WHERE SEX_UPON_OUTCOME LIKE 'Intact%'
)
ORDER BY ANIMAL_ID